{
 "title": "Fraud Detection Pipeline Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Minimum Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(http_request_duration_seconds_sum{handler=\"/predict\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(http_request_duration_seconds_sum{handler=\"/predict\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (RPS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fraud-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predict API – Request Duration Rate",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/predict\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/predict\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total{job=\"fraud-api\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic by Endpoint promql Copy Edit",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total{job=\"fraud-api\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App uptime in hours:",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"fraud-api\"}) / 3600\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage as Gauge [Fraud API(Up) and Prometheus(Down)]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fraud-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Average GC pause time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"prometheus\"}[$__rate_interval]) / (rate(go_gc_duration_seconds_count{job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 vs p99 latency (95th percentile vs 99th percentile):",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"fraud-api\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{job=\"fraud-api\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory growth rate (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap allocated memory (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident memory usage (bytes) of Prometheus:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}